/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CButton: typeof import('./src/components/c-button/c-button.vue')['default']
    Dialog: typeof import('./src/components/dialog/dialog.vue')['default']
    Dropdown: typeof import('./src/components/dropdown/dropdown.vue')['default']
    Message: typeof import('./src/components/message/message.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
